import os

from sqlalchemy import inspect, text

from extensions import db
from models.challenge import Challenge


FRONTEND_FLAGS = {
    "FLAG_META_TAG_FRAGMENT": "CTF{mirkwood_beacon_1983}",
    "FLAG_APP_SHELL_MARKER": "CTF{the_gate_left_a_mark}",
    "FLAG_HOME_INVISIBLE_FRAGMENT": "CTF{lights_spell_the_warning}",
    "FLAG_CSS_CLASS_FRAGMENT": "CTF{hellfire_hides_in_style}",
    "FLAG_NAVBAR_TRACE": "CTF{channel_six_is_listening}",
    "FLAG_SUBMIT_PANEL_TRACE": "CTF{red_door_accepts_the_signal}",
}

EVENT_CHALLENGES = [
    {
        "slug": "meta-tag-fragment",
        "title": "Hawkins Meta Beacon",
        "category": "Frontend Forensics",
        "difficulty": "Easy",
        "description": "A Hawkins-style beacon is attached to the document before the page even renders.",
        "hint": "Not all useful data is visible in the rendered page.",
        "points": 50,
        "order_index": 5,
        "env_key": "FLAG_META_TAG_FRAGMENT",
        "fallback": FRONTEND_FLAGS["FLAG_META_TAG_FRAGMENT"],
    },
    {
        "slug": "app-shell-marker",
        "title": "Upside Down Shell Marker",
        "category": "Frontend Forensics",
        "difficulty": "Easy",
        "description": "The outer application shell carries a marker from the Upside Down.",
        "hint": "The outer shell of the interface carries more than styling.",
        "points": 50,
        "order_index": 6,
        "env_key": "FLAG_APP_SHELL_MARKER",
        "fallback": FRONTEND_FLAGS["FLAG_APP_SHELL_MARKER"],
    },
    {
        "slug": "home-invisible-fragment",
        "title": "Phantom Hawkins Signal",
        "category": "Frontend Forensics",
        "difficulty": "Easy",
        "description": "A phantom signal is present on the homepage, but not visible to normal operators.",
        "hint": "Invisible does not always mean absent.",
        "points": 50,
        "order_index": 7,
        "env_key": "FLAG_HOME_INVISIBLE_FRAGMENT",
        "fallback": FRONTEND_FLAGS["FLAG_HOME_INVISIBLE_FRAGMENT"],
    },
    {
        "slug": "css-class-fragment",
        "title": "Hellfire CSS Trace",
        "category": "Frontend Forensics",
        "difficulty": "Easy",
        "description": "Some protocol fragments are hidden in styling rather than markup.",
        "hint": "The visual layer can hide readable traces.",
        "points": 50,
        "order_index": 8,
        "env_key": "FLAG_CSS_CLASS_FRAGMENT",
        "fallback": FRONTEND_FLAGS["FLAG_CSS_CLASS_FRAGMENT"],
    },
    {
        "slug": "navbar-trace",
        "title": "Walkie Nav Trace",
        "category": "Frontend Forensics",
        "difficulty": "Easy",
        "description": "The navigation layer carries a walkie-style trace.",
        "hint": "Navigation can carry metadata beyond links.",
        "points": 50,
        "order_index": 9,
        "env_key": "FLAG_NAVBAR_TRACE",
        "fallback": FRONTEND_FLAGS["FLAG_NAVBAR_TRACE"],
    },
    {
        "slug": "submit-panel-trace",
        "title": "Gate Submit Fragment",
        "category": "Frontend Forensics",
        "difficulty": "Easy",
        "description": "The submission panel carries a quiet trace for those who inspect before transmitting.",
        "hint": "Before sending a signal, inspect the gate that receives it.",
        "points": 50,
        "order_index": 10,
        "env_key": "FLAG_SUBMIT_PANEL_TRACE",
        "fallback": FRONTEND_FLAGS["FLAG_SUBMIT_PANEL_TRACE"],
    },
    {
        "slug": "console-whisper",
        "title": "Static on Channel 6",
        "category": "Frontend Forensics",
        "difficulty": "Easy",
        "description": "A client-side lab emits radio static. Listen where browser scripts speak.",
        "hint": "Client-side scripts sometimes speak where users do not look.",
        "points": 50,
        "order_index": 20,
        "env_key": "FLAG_CONSOLE_WHISPER",
        "fallback": "CTF{static_speaks_first}",
    },
    {
        "slug": "hidden-attribute",
        "title": "Hawkins Lab Attribute",
        "category": "Frontend Forensics",
        "difficulty": "Easy",
        "description": "A Hawkins Lab marker is attached to an element.",
        "hint": "Look for data attached to elements, not just visible text.",
        "points": 50,
        "order_index": 30,
        "env_key": "FLAG_HIDDEN_ATTRIBUTE",
        "fallback": "CTF{lab_tags_never_lie}",
    },
    {
        "slug": "local-storage-leak",
        "title": "Browser Memory Trace",
        "category": "Frontend Forensics",
        "difficulty": "Easy",
        "description": "The browser remembers more than it should. Recover the leaked local storage value.",
        "hint": "Some traces remain in the browser after a page is visited.",
        "points": 75,
        "order_index": 40,
        "env_key": "FLAG_LOCAL_STORAGE_LEAK",
        "fallback": "CTF{memory_survives_the_breach}",
    },
    {
        "slug": "ghosts-in-robots",
        "title": "Crawlers at the Gate",
        "category": "Recon",
        "difficulty": "Easy",
        "description": "A gate-related clue was left for crawlers. Read the standard crawler instruction file.",
        "hint": "Crawlers leave clues about places they should avoid.",
        "points": 75,
        "order_index": 50,
        "env_key": "FLAG_ROBOTS_GHOST",
        "fallback": "CTF{crawlers_avoid_the_gate}",
    },
    {
        "slug": "forgotten-humans",
        "title": "Hawkins Lab Staff Note",
        "category": "Recon",
        "difficulty": "Easy",
        "description": "A lab note was written for humans, not machines.",
        "hint": "Some files are written for humans rather than machines.",
        "points": 75,
        "order_index": 60,
        "env_key": "FLAG_FORGOTTEN_HUMANS",
        "fallback": "CTF{humans_left_the_note}",
    },
    {
        "slug": "echoes-in-the-header",
        "title": "Signal Above the Body",
        "category": "Web Exploitation",
        "difficulty": "Easy",
        "description": "The body says little, but the signal travels above it.",
        "hint": "The body is not the only part of a web response.",
        "points": 100,
        "order_index": 70,
        "env_key": "FLAG_HEADER_ECHO",
        "fallback": "CTF{headers_echo_from_below}",
    },
    {
        "slug": "encoded-transmission",
        "title": "Encoded Walkie Transmission",
        "category": "Crypto",
        "difficulty": "Medium",
        "description": "A walkie transmission was archived in a common encoding. Identify and decode it.",
        "hint": "The payload is readable once its encoding is understood.",
        "points": 100,
        "order_index": 80,
        "env_key": "FLAG_ENCODED_TRANSMISSION",
        "fallback": "CTF{walkie_payload_decoded}",
    },
    {
        "slug": "reversed-signal",
        "title": "Reversed Red Signal",
        "category": "Crypto",
        "difficulty": "Medium",
        "description": "The red signal is complete, but it is facing the wrong direction. Reverse it.",
        "hint": "The signal is complete, but its order is wrong.",
        "points": 100,
        "order_index": 90,
        "env_key": "FLAG_REVERSED_SIGNAL",
        "fallback": "CTF{vecna_signal_reversed}",
    },
    {
        "slug": "shadow-search",
        "title": "Hawkins Archive Search",
        "category": "Web Exploitation",
        "difficulty": "Medium",
        "description": "The Hawkins archive search reveals different records based on terms you query.",
        "hint": "Try archive-related terms and observe how the records change.",
        "points": 125,
        "order_index": 100,
        "env_key": "FLAG_SHADOW_SEARCH",
        "fallback": "CTF{archive_knows_the_word}",
    },
    {
        "slug": "vault-injection",
        "title": "Lab Vault Breach",
        "category": "Web Exploitation",
        "difficulty": "Hard",
        "description": "A lab vault performs unsafe SQL lookups in an isolated training database.",
        "hint": "The vault trusts input too much. The shape of returned records matters.",
        "points": 150,
        "order_index": 110,
        "env_key": "FLAG_VAULT_INJECTION",
        "fallback": "CTF{vault_trusts_the_wrong_input}",
    },

    {
        "slug": "main-render-signal",
        "title": "Main Render Signal",
        "category": "Frontend Forensics",
        "difficulty": "Easy",
        "description": "The first render leaves a signal on the page itself.",
        "hint": "The document changes as the client application starts.",
        "points": 50,
        "order_index": 120,
        "env_key": "FLAG_MAIN_RENDER_SIGNAL",
        "fallback": "CTF{render_opened_the_gate}",
    },
    {
        "slug": "footer-static-trace",
        "title": "Footer Static Trace",
        "category": "Frontend Forensics",
        "difficulty": "Easy",
        "description": "Static sometimes settles at the bottom of the transmission.",
        "hint": "The lower edge of the interface carries more than text.",
        "points": 50,
        "order_index": 130,
        "env_key": "FLAG_FOOTER_STATIC_TRACE",
        "fallback": "CTF{static_at_the_footer}",
    },
    {
        "slug": "red-room-intel-note",
        "title": "Red Room Intel Note",
        "category": "Frontend Forensics",
        "difficulty": "Easy",
        "description": "The briefing room contains a hidden note from the incident team.",
        "hint": "Briefings can carry metadata as well as visible instructions.",
        "points": 50,
        "order_index": 140,
        "env_key": "FLAG_RED_ROOM_INTEL_NOTE",
        "fallback": "CTF{red_room_note_found}",
    },
    {
        "slug": "rules-gate-marker",
        "title": "Rules Gate Marker",
        "category": "Frontend Forensics",
        "difficulty": "Easy",
        "description": "The rules page marks the boundary of the operation.",
        "hint": "The rules surface has a marker beyond the list itself.",
        "points": 50,
        "order_index": 150,
        "env_key": "FLAG_RULES_GATE_MARKER",
        "fallback": "CTF{rules_mark_the_boundary}",
    },
    {
        "slug": "api-client-whisper",
        "title": "API Client Whisper",
        "category": "Frontend Forensics",
        "difficulty": "Medium",
        "description": "The browser client adds a quiet trace while talking to the backend.",
        "hint": "Observe what the client sends when it talks to the API.",
        "points": 75,
        "order_index": 160,
        "env_key": "FLAG_API_CLIENT_WHISPER",
        "fallback": "CTF{client_whispers_in_headers}",
    },
    {
        "slug": "radio-log-file",
        "title": "Radio Log File",
        "category": "Recon",
        "difficulty": "Easy",
        "description": "An old radio log was left among public assets.",
        "hint": "Static files can contain more than images.",
        "points": 75,
        "order_index": 170,
        "env_key": "FLAG_RADIO_LOG_FILE",
        "fallback": "CTF{radio_log_after_midnight}",
    },
    {
        "slug": "classified-hawkins-json",
        "title": "Classified Hawkins JSON",
        "category": "Recon",
        "difficulty": "Easy",
        "description": "A structured incident note was left where public assets are served.",
        "hint": "Some public files are meant for machines but readable by operators.",
        "points": 75,
        "order_index": 180,
        "env_key": "FLAG_CLASSIFIED_HAWKINS_JSON",
        "fallback": "CTF{json_file_from_hawkins}",
    },
    {
        "slug": "hawkins-cookie-signal",
        "title": "Hawkins Cookie Signal",
        "category": "Web Exploitation",
        "difficulty": "Easy",
        "description": "A lab response leaves a small browser-side token behind.",
        "hint": "Responses can store small traces in the browser.",
        "points": 75,
        "order_index": 190,
        "env_key": "FLAG_HAWKINS_COOKIE_SIGNAL",
        "fallback": "CTF{cookie_from_the_lab}",
    },
    {
        "slug": "channel-eleven-frequency",
        "title": "Channel Eleven Frequency",
        "category": "Web Exploitation",
        "difficulty": "Medium",
        "description": "The frequency endpoint changes when tuned to the right channel.",
        "hint": "Try meaningful channel numbers and watch the signal response.",
        "points": 100,
        "order_index": 200,
        "env_key": "FLAG_CHANNEL_ELEVEN_FREQUENCY",
        "fallback": "CTF{eleven_found_the_frequency}",
    },
    {
        "slug": "debug-lab-leak",
        "title": "Debug Lab Leak",
        "category": "Web Exploitation",
        "difficulty": "Medium",
        "description": "A lab diagnostic endpoint reveals more when debug behavior is enabled.",
        "hint": "Some endpoints behave differently when diagnostic switches are set.",
        "points": 100,
        "order_index": 210,
        "env_key": "FLAG_DEBUG_LAB_LEAK",
        "fallback": "CTF{debug_mode_broke_containment}",
    },

    {
        "slug": "lab-record-drift",
        "title": "Lab Record Drift",
        "category": "API Security",
        "difficulty": "Medium",
        "description": "A lab record endpoint returns records by identifier. Check whether every record is protected equally.",
        "hint": "Records are often separated by identifiers. Check whether the server trusts the number too much.",
        "points": 125,
        "order_index": 220,
        "env_key": "FLAG_LAB_RECORD_DRIFT",
        "fallback": "CTF{records_should_check_owners}",
    },
    {
        "slug": "archive-slip",
        "title": "Archive Slip",
        "category": "Web Exploitation",
        "difficulty": "Medium",
        "description": "The archive reads named files from a training collection. Find out whether restricted names are handled safely.",
        "hint": "Some archives trust filenames more than they should. Think about relative paths, not real server files.",
        "points": 125,
        "order_index": 230,
        "env_key": "FLAG_ARCHIVE_SLIP",
        "fallback": "CTF{archives_should_not_trust_paths}",
    },
    {
        "slug": "paper-badge",
        "title": "Paper Badge",
        "category": "Web Exploitation",
        "difficulty": "Medium",
        "description": "A badge scanner accepts an encoded paper badge. Inspect what the badge really contains.",
        "hint": "Not every token is encrypted. Some are only encoded and can be rebuilt.",
        "points": 125,
        "order_index": 240,
        "env_key": "FLAG_PAPER_BADGE",
        "fallback": "CTF{encoded_badges_are_not_auth}",
    },
    {
        "slug": "control-room-method",
        "title": "Control Room Method",
        "category": "Web Exploitation",
        "difficulty": "Medium",
        "description": "The control room responds differently depending on how the request is made.",
        "hint": "Some doors do not open when you only knock politely. Try asking with a different HTTP method.",
        "points": 100,
        "order_index": 250,
        "env_key": "FLAG_CONTROL_ROOM_METHOD",
        "fallback": "CTF{methods_change_the_message}",
    },
    {
        "slug": "clearance-override",
        "title": "Clearance Override",
        "category": "API Security",
        "difficulty": "Medium",
        "description": "A clearance API checks JSON fields. The visible example may not be the whole request shape.",
        "hint": "The interface may hide fields, but the API can still read them.",
        "points": 150,
        "order_index": 260,
        "env_key": "FLAG_CLEARANCE_OVERRIDE",
        "fallback": "CTF{hidden_fields_open_doors}",
    },
    {
        "slug": "signal-stack",
        "title": "Signal Stack",
        "category": "Encoding",
        "difficulty": "Easy",
        "description": "A public signal capture was wrapped in multiple simple encodings. Unwrap the stack.",
        "hint": "If the first layer becomes pairs of byte-like characters, keep decoding.",
        "points": 100,
        "order_index": 270,
        "env_key": "FLAG_SIGNAL_STACK",
        "fallback": "CTF{signal_stack_unwrapped}",
    },
    {
        "slug": "shifted-broadcast",
        "title": "Shifted Broadcast",
        "category": "Crypto",
        "difficulty": "Medium",
        "description": "A broadcast is readable only after reversing a simple rotation.",
        "hint": "Old messages sometimes shift letters rather than hide them deeply.",
        "points": 100,
        "order_index": 280,
        "env_key": "FLAG_SHIFTED_BROADCAST",
        "fallback": "CTF{rotation_reveals_the_broadcast}",
    },
    {
        "slug": "final-gate",
        "title": "The Final Gate",
        "category": "Logic Bugs",
        "difficulty": "Hard",
        "description": "The final gate requires multiple values recovered from separate training labs.",
        "hint": "The final lock does not have one key. Gather values from records, archive notes, badge data, and control signals.",
        "points": 250,
        "order_index": 290,
        "env_key": "FLAG_FINAL_GATE",
        "fallback": "CTF{four_keys_close_the_shadow_gate}",
    },
]


def flag_value(env_key, fallback):
    return os.getenv(env_key, fallback)


def ensure_phase2_schema():
    inspector = inspect(db.engine)
    if "challenges" not in inspector.get_table_names():
        return

    existing_columns = {column["name"] for column in inspector.get_columns("challenges")}
    additions = {
        "difficulty": "ALTER TABLE challenges ADD COLUMN difficulty VARCHAR(40)",
        "hint": "ALTER TABLE challenges ADD COLUMN hint TEXT",
        "order_index": "ALTER TABLE challenges ADD COLUMN order_index INTEGER",
    }

    with db.engine.begin() as connection:
        for column_name, ddl in additions.items():
            if column_name not in existing_columns:
                connection.execute(text(ddl))


def seed_event_challenges():
    ensure_phase2_schema()
    event_slugs = {item["slug"] for item in EVENT_CHALLENGES}

    for item in EVENT_CHALLENGES:
        challenge = Challenge.query.filter_by(slug=item["slug"]).first()
        data = {
            "slug": item["slug"],
            "title": item["title"],
            "category": item["category"],
            "description": item["description"],
            "points": item["points"],
            "flag": flag_value(item["env_key"], item["fallback"]),
            "difficulty": item["difficulty"],
            "hint": item["hint"],
            "order_index": item["order_index"],
            "is_active": True,
        }

        if challenge:
            for key, value in data.items():
                setattr(challenge, key, value)
        else:
            db.session.add(Challenge(**data))

    Challenge.query.filter(~Challenge.slug.in_(event_slugs)).update(
        {Challenge.is_active: False},
        synchronize_session=False,
    )

    db.session.commit()
